language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true
cache: pip
install:
  - travis_retry pip install -U .
  - travis_retry pip install -U invoke flake8 pytest
  - travis_retry pip install -r requirements.txt
script: invoke test